export const ECUADOR_CITIES = [
    { value: 'Quito', label: 'Quito' },
    { value: 'Guayaquil', label: 'Guayaquil' },
    { value: 'Cuenca', label: 'Cuenca' },
    { value: 'Santo Domingo', label: 'Santo Domingo' },
    { value: 'Manta', label: 'Manta' },
    { value: 'Quevedo', label: 'Quevedo' },
    { value: 'Machala', label: 'Machala' },
    { value: 'Portoviejo', label: 'Portoviejo' },
    { value: 'Duran', label: 'Durán' },
    { value: 'Loja', label: 'Loja' },
    { value: 'Ambato', label: 'Ambato' },
    { value: 'Esmeraldas', label: 'Esmeraldas' },
    { value: 'Riobamba', label: 'Riobamba' },
    { value: 'Milagro', label: 'Milagro' },
    { value: 'Ibarra', label: 'Ibarra' },
    { value: 'La Libertad', label: 'La Libertad' },
    { value: 'Babahoyo', label: 'Babahoyo' },
    { value: 'Sangolqui', label: 'Sangolquí' },
    { value: 'Daule', label: 'Daule' },
    { value: 'Latacunga', label: 'Latacunga' },
    { value: 'Tulcan', label: 'Tulcán' },
    { value: 'Chone', label: 'Chone' },
    { value: 'Pasaje', label: 'Pasaje' },
    { value: 'Santa Rosa', label: 'Santa Rosa' },
    { value: 'Nueva Loja', label: 'Nueva Loja (Lago Agrio)' },
    { value: 'Huaquillas', label: 'Huaquillas' },
    { value: 'Salinas', label: 'Salinas' },
    { value: 'Otavalo', label: 'Otavalo' },
    { value: 'Cayambe', label: 'Cayambe' },
    { value: 'Azogues', label: 'Azogues' },
    { value: 'Puyo', label: 'Puyo' },
    { value: 'Tena', label: 'Tena' },
    { value: 'Macas', label: 'Macas' },
    { value: 'Zamora', label: 'Zamora' },
    { value: 'Remoto', label: 'Remoto / Multinacional' }
];
